# Generated by Django 3.1.7 on 2021-02-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'Риелтор', 'verbose_name_plural': 'Риелторы'},
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не определено'), (1, 'Продает'), (2, 'Покупает'), (3, 'Продает/покупает')], default=0, verbose_name='Статус'),
        ),
    ]
