# Generated by Django 3.1.7 on 2021-02-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20210221_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
    ]
